extends:
    - 'plugin:prettier/recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
plugins:
    - '@typescript-eslint'
    - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
    project: './tsconfig.json'
env:
    es6: true
rules:
    # use TS
    valid-jsdoc: 0
    indent: 0
    quotes: 0
    comma-dangle: ['error', 'only-multiline']
    '@typescript-eslint/no-unused-vars': 2
    'object-curly-spacing':
        - 1
        - never
    'prettier/prettier':
        - 2
        - endOfLine: auto
